language: objective-c
osx_image: xcode9
env: 
global:
- LC_CTYPE=en_US.UTF-8
- LANG=en_US.UTF-8
- WORKSPACE=Mo9Framework.xcworkspace
- IOS_FRAMEWORK_SCHEME="mo9Library"
- IOS_SDK=iphonesimulator11.0
matrix:
- DESTINATION="OS=11.0,name=iPhone 8 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
- DESTINATION="OS=10.0,name=iPhone 7 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
- DESTINATION="OS=9.0,name=iPhone 5"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
- DESTINATION="OS=8.1,name=iPhone 4S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
- DESTINATION="OS=8.2,name=iPhone 5"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
- DESTINATION="OS=8.3,name=iPhone 5S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
- DESTINATION="OS=8.4,name=iPhone 6"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
- DESTINATION="OS=9.0,name=iPhone 6 Plus"      SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
- DESTINATION="OS=9.1,name=iPhone 6S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
- DESTINATION="OS=9.2,name=iPhone 6S Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
script:
- xcodebuild -showsdks
- xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION"
  -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
deploy:
  provider: releases
  api_key:
    secure: c7IvQhTG0kuarZJCN4reFEBjPxZjv9jLnT3Xzd9BKg1xaeNT83MXg81l2VRTEIi0i11XokbPrPJmDNwZTRNJG8J8GmiwQ/dHLx/1IJMtSp6Pzuj4etBT6ilgrMDXo9TxSEb3Flod4LKpg+VxvWO1axWyC/CBCqQxjQsFJyV2btMrFn7W7XrWAwhQWyR4wswnXh7UtaxjxBq2Mqv1OnlPTw0BXnshD3ZzF5YWyXp+Q25TgqHQgECDdJ8p2hRzYXAUiEt15udyPBPyLjfqUoLqRwpFIVgKPnIv2m2cirjJd8tv5N8E49gs7RiEaDNmqfl4psqnV2VrvFbgdHY1az5ujO1WkjrfsoMJeFE73TYOegfvf8qRKDqn3r91J3j2feRAQf4zFr1zQlobwyqXtAeyEMf1YVsrntI65MOHxDTN7H3Mu8hVEEWajR7+jfQxk5WwQulgV/T/HZ4zvditaosIf/lNi/ztJYuT3sLYPB/xg3ebR4C1Uf2/DnV55tC44Lt0ELRRJekki/oXScLkpFPdG8b3hFTDLfQl8JkY55YUfkeUOxW/T5hEdZ/rkB9QAbpEY7Bv62HIcoKHlQEoPFnOQMuZHKiN4u4Nmch0A3Rc55M8RvxdZpTsyA3264R+oGVhJQMTRHLuGIM+UVqn6cSBAiOEvgCJH0f3lEYBr+BC6MI=
  file: ''
  on:
    repo: sumlunmao/MMLib
